// @generated by diesel - matches migrations/004_publish_job_scheduler/up.sql

diesel::table! {
    account_links (nostr_pubkey) {
        nostr_pubkey -> Text,
        did -> Nullable<Text>,
        handle -> Text,
        crosspost_enabled -> Bool,
        signing_key_id -> Text,
        plc_rotation_key_ref -> Text,
        provisioning_state -> Text,
        provisioning_error -> Nullable<Text>,
        publish_backfill_state -> Text,
        publish_backfill_started_at -> Nullable<Timestamptz>,
        publish_backfill_completed_at -> Nullable<Timestamptz>,
        publish_backfill_error -> Nullable<Text>,
        disabled_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    provisioning_keys (key_ref) {
        key_ref -> Text,
        key_purpose -> Text,
        public_key_hex -> Text,
        encrypted_secret -> Binary,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    ingest_offsets (source_name) {
        source_name -> Text,
        last_event_id -> Text,
        last_created_at -> Timestamptz,
    }
}

diesel::table! {
    asset_manifest (source_sha256) {
        source_sha256 -> Text,
        blossom_url -> Nullable<Text>,
        at_blob_cid -> Text,
        mime -> Text,
        bytes -> Int8,
        is_derivative -> Bool,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    record_mappings (nostr_event_id) {
        nostr_event_id -> Text,
        did -> Text,
        collection -> Text,
        rkey -> Text,
        at_uri -> Text,
        cid -> Nullable<Text>,
        status -> Text,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    moderation_actions (id) {
        id -> Int8,
        subject_type -> Text,
        subject_id -> Text,
        action -> Text,
        origin -> Text,
        reason -> Nullable<Text>,
        state -> Text,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    publish_jobs (nostr_event_id) {
        nostr_event_id -> Text,
        nostr_pubkey -> Text,
        event_created_at -> Timestamptz,
        event_payload -> Jsonb,
        job_source -> Text,
        attempt -> Int4,
        state -> Text,
        error -> Nullable<Text>,
        lease_owner -> Nullable<Text>,
        lease_expires_at -> Nullable<Timestamptz>,
        completed_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    labeler_events (seq) {
        seq -> Int8,
        src_did -> Text,
        subject_uri -> Text,
        subject_cid -> Nullable<Text>,
        val -> Text,
        neg -> Bool,
        nostr_event_id -> Nullable<Text>,
        sha256 -> Nullable<Text>,
        origin -> Text,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    inbound_labels (id) {
        id -> Int8,
        labeler_did -> Text,
        subject_uri -> Text,
        val -> Text,
        neg -> Bool,
        nostr_event_id -> Nullable<Text>,
        sha256 -> Nullable<Text>,
        divine_label -> Nullable<Text>,
        review_state -> Text,
        reviewed_by -> Nullable<Text>,
        reviewed_at -> Nullable<Timestamptz>,
        raw_json -> Nullable<Text>,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    appview_repos (did) {
        did -> Text,
        handle -> Nullable<Text>,
        head -> Nullable<Text>,
        rev -> Nullable<Text>,
        active -> Bool,
        last_backfilled_at -> Nullable<Timestamptz>,
        last_seen_seq -> Nullable<Int8>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    appview_profiles (did) {
        did -> Text,
        handle -> Nullable<Text>,
        display_name -> Nullable<Text>,
        description -> Nullable<Text>,
        website -> Nullable<Text>,
        avatar_cid -> Nullable<Text>,
        banner_cid -> Nullable<Text>,
        created_at -> Nullable<Timestamptz>,
        raw_json -> Nullable<Text>,
        indexed_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    appview_posts (uri) {
        uri -> Text,
        did -> Text,
        rkey -> Text,
        record_cid -> Nullable<Text>,
        created_at -> Timestamptz,
        text -> Text,
        langs_json -> Nullable<Text>,
        embed_blob_cid -> Nullable<Text>,
        embed_alt -> Nullable<Text>,
        aspect_ratio_width -> Nullable<Int4>,
        aspect_ratio_height -> Nullable<Int4>,
        raw_json -> Nullable<Text>,
        search_text -> Text,
        indexed_at -> Timestamptz,
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    appview_media_views (did, blob_cid) {
        did -> Text,
        blob_cid -> Text,
        playlist_url -> Text,
        thumbnail_url -> Nullable<Text>,
        mime_type -> Text,
        bytes -> Int8,
        ready -> Bool,
        last_derived_at -> Nullable<Timestamptz>,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    appview_service_state (state_key) {
        state_key -> Text,
        state_value -> Nullable<Text>,
        updated_at -> Timestamptz,
    }
}

diesel::joinable!(record_mappings -> account_links (did));
diesel::joinable!(appview_profiles -> appview_repos (did));
diesel::joinable!(appview_posts -> appview_profiles (did));

diesel::allow_tables_to_appear_in_same_query!(
    account_links,
    provisioning_keys,
    ingest_offsets,
    asset_manifest,
    record_mappings,
    moderation_actions,
    publish_jobs,
    labeler_events,
    inbound_labels,
    appview_repos,
    appview_profiles,
    appview_posts,
    appview_media_views,
    appview_service_state,
);
