// @generated by diesel - matches migrations/001_bridge_tables/up.sql

diesel::table! {
    account_links (nostr_pubkey) {
        nostr_pubkey -> Text,
        did -> Text,
        handle -> Text,
        crosspost_enabled -> Bool,
        signing_key_id -> Text,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    ingest_offsets (source_name) {
        source_name -> Text,
        last_event_id -> Text,
        last_created_at -> Timestamptz,
    }
}

diesel::table! {
    asset_manifest (source_sha256) {
        source_sha256 -> Text,
        blossom_url -> Nullable<Text>,
        at_blob_cid -> Text,
        mime -> Text,
        bytes -> Int8,
        is_derivative -> Bool,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    record_mappings (nostr_event_id) {
        nostr_event_id -> Text,
        did -> Text,
        collection -> Text,
        rkey -> Text,
        at_uri -> Text,
        cid -> Nullable<Text>,
        status -> Text,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    moderation_actions (id) {
        id -> Int8,
        subject_type -> Text,
        subject_id -> Text,
        action -> Text,
        origin -> Text,
        reason -> Nullable<Text>,
        state -> Text,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    publish_jobs (nostr_event_id) {
        nostr_event_id -> Text,
        attempt -> Int4,
        state -> Text,
        error -> Nullable<Text>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::joinable!(record_mappings -> account_links (did));

diesel::allow_tables_to_appear_in_same_query!(
    account_links,
    ingest_offsets,
    asset_manifest,
    record_mappings,
    moderation_actions,
    publish_jobs,
);
