// @generated by diesel - matches migrations/001_bridge_tables/up.sql

diesel::table! {
    account_links (nostr_pubkey) {
        nostr_pubkey -> Text,
        did -> Nullable<Text>,
        handle -> Text,
        crosspost_enabled -> Bool,
        signing_key_id -> Text,
        plc_rotation_key_ref -> Text,
        provisioning_state -> Text,
        provisioning_error -> Nullable<Text>,
        disabled_at -> Nullable<Timestamptz>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    ingest_offsets (source_name) {
        source_name -> Text,
        last_event_id -> Text,
        last_created_at -> Timestamptz,
    }
}

diesel::table! {
    asset_manifest (source_sha256) {
        source_sha256 -> Text,
        blossom_url -> Nullable<Text>,
        at_blob_cid -> Text,
        mime -> Text,
        bytes -> Int8,
        is_derivative -> Bool,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    record_mappings (nostr_event_id) {
        nostr_event_id -> Text,
        did -> Text,
        collection -> Text,
        rkey -> Text,
        at_uri -> Text,
        cid -> Nullable<Text>,
        status -> Text,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    moderation_actions (id) {
        id -> Int8,
        subject_type -> Text,
        subject_id -> Text,
        action -> Text,
        origin -> Text,
        reason -> Nullable<Text>,
        state -> Text,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    publish_jobs (nostr_event_id) {
        nostr_event_id -> Text,
        attempt -> Int4,
        state -> Text,
        error -> Nullable<Text>,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    labeler_events (seq) {
        seq -> Int8,
        src_did -> Text,
        subject_uri -> Text,
        subject_cid -> Nullable<Text>,
        val -> Text,
        neg -> Bool,
        nostr_event_id -> Nullable<Text>,
        sha256 -> Nullable<Text>,
        origin -> Text,
        created_at -> Timestamptz,
    }
}

diesel::table! {
    inbound_labels (id) {
        id -> Int8,
        labeler_did -> Text,
        subject_uri -> Text,
        val -> Text,
        neg -> Bool,
        nostr_event_id -> Nullable<Text>,
        sha256 -> Nullable<Text>,
        divine_label -> Nullable<Text>,
        review_state -> Text,
        reviewed_by -> Nullable<Text>,
        reviewed_at -> Nullable<Timestamptz>,
        raw_json -> Nullable<Text>,
        created_at -> Timestamptz,
    }
}

diesel::joinable!(record_mappings -> account_links (did));

diesel::allow_tables_to_appear_in_same_query!(
    account_links,
    ingest_offsets,
    asset_manifest,
    record_mappings,
    moderation_actions,
    publish_jobs,
    labeler_events,
    inbound_labels,
);
